runtime: go111

env_variables:
  # Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
  # Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
  # For Cloud SQL 2nd generation instances, this should be in the form of "project:region:instance".
  CLOUDSQL_CONNECTION_NAME: tyler-website:us-east1:tyler-website-db
  # Replace username and password if you aren't using the root user.
  CLOUDSQL_USER: postgres
  CLOUDSQL_PASSWORD: rAsIH0MM1C2ka4sq
  POSTGRES_CONNECTION: postgres://jhtlhxyr:mOxqh49SFZ5uJi-I6AOSb9Yjdu8UdGne@baasu.db.elephantsql.com:5432/jhtlhxyr?sslmode=disable

  # If you're testing locally using the Cloud SQL proxy with TCP,
  # instead set this environment variable:
  # POSTGRES_CONNECTION="user=postgres password=rAsIH0MM1C2ka4sq dbname=postgres sslmode=disable"